apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  application-name: dev-prueba-doc
resources:
- buildconfig-credsuc-servicio-btt.yaml
- configmap-credsuc-configmap-logger.yaml
- configmap-credsucurconfig.yaml
- deploymentconfig-credsuc-servicio-btt.yaml
- imagestream-credsuc-servicio-btt.yaml
- route-credsuc-servicio-btt.yaml
- service-credsuc-servicio-btt.yaml
