apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  variant: development
bases:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/host
      value: credsuc-servicio-btt-dev-prueba-doc.apps.ocp-noprod.cclh.int
  target:
    kind: Route
